name: 'Brocolito'
description: 'Prepare Brocolito CLI'
inputs:
  token:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.
      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.
      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}
  install_dir:
    description: The directory where to place the symbolic link for aliased execution
    default: ${{ github.path }}

runs:
  using: composite
  steps:
    - uses: ./.github/actions/pnpm-install
      with:
        target: .github/cli
    - run: pnpm build
      shell: bash
      working-directory: .github/cli
    - run: |
        chmod a+x .github/cli/build/index.cjs.js
        cp -s .github/cli/build/index.cjs.js ${{ inputs.install_dir }}/brocolito
      shell: bash
