name: PR

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pnpm-install
        with:
          target: .github/cli
      - run: pnpm build
        working-directory: .github/cli
      - run: node .github/cli
        id: foo
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo ${{ steps.foo.outputs.changed_files }}
