name: Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        env:
          NODE_VERSION: "16"
        with:
          node-version: "${{ env.NODE_VERSION }}"
      - run: node .github/cli
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
