name: PR

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/brocolito-setup
      - run: bro changed_files
        id: find-changed-files
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - run: echo ${{ steps.find-changed-files.outputs.changed_files }}
